model:
  class_path: anomalib.models.Padim
  init_args:
    backbone: resnet18
    layers:
      - layer1
      - layer2
      - layer3
data:
  name: folder
  class_path: anomalib.data.Folder
  init_args:
    name: pcb1   # Folderクラスの必須引数
    root: /shared/data/pcb1/Data/Images   # main.py/config.yaml と同階層に pcb1 を配置する想定
    normal_dir: Normal
    abnormal_dir: Anomaly
    normal_test_dir: Normal  # テスト用の正常画像ディレクトリを指定
    extensions:
      - .jpg
      - .jpeg
      - .JPG
      - .JPEG
      - .png
      - .PNG
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 0
trainer:
  max_epochs: 2
  accelerator: gpu
  devices: 1
  deterministic: true
  enable_model_summary: false
  log_every_n_steps: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 0
metrics:
  image:
    - AUROC
    - AUPR
    - F1Score
  pixel:
    - AUROC
    - AUPR
    - F1Score

threshold:
  method: adaptive
