jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, prod]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy (pull & up)
        shell: bash
        run: |
          set -euo pipefail
          docker compose \
            --env-file /etc/leadersboard/prod.env \
            -f docker-compose.yml -f docker-compose.prod.yml pull

          docker compose \
            --env-file /etc/leadersboard/prod.env \
            -f docker-compose.yml -f docker-compose.prod.yml up -d --no-build
